# -*- coding: utf-8 -*-
"""DPP_Prj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpwAnMS4gmhLhxc3vwj0hoRxuV0hjxax
"""

import pandas as pd

url = "https://raw.githubusercontent.com/swapnilsaurav/Dataset/refs/heads/master/hotel_bookings.csv"
df = pd.read_csv(url)

df.head()



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, RobustScaler, Binarizer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, f1_score

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans

from sklearn.datasets import make_classification
from sklearn.feature_selection import mutual_info_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import PolynomialFeatures

"""TASK1 - BASELINE + " WHAT IS A FEATURE"
"""

import pandas as pd

url = "https://raw.githubusercontent.com/swapnilsaurav/Dataset/refs/heads/master/hotel_bookings.csv"
df = pd.read_csv(url)

df = df.dropna(subset=['country'])

X = df.drop('is_canceled', axis=1)
y = df['is_canceled']

num_cols = X.select_dtypes(include='number').columns
cat_cols = X.select_dtypes(exclude='number').columns

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

preprocessor = ColumnTransformer([
    ("num", SimpleImputer(strategy="median"), num_cols),
    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

model = Pipeline([
    ("prep", preprocessor),
    ("clf", LogisticRegression(max_iter=1000))
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)
print("Baseline F1:", f1_score(y_test, model.predict(X_test)))

"""TASK 2 Curse of Dimensionality Demo


"""

from sklearn.datasets import make_classification
from scipy.spatial.distance import pdist
import matplotlib.pyplot as plt

for d in [2, 10, 50, 200]:
    # Set n_informative=1, n_redundant=0, n_repeated=0 and n_clusters_per_class=1 to avoid ValueError
    X, _ = make_classification(n_samples=500, n_features=d, n_informative=1, n_redundant=0, n_repeated=0, n_clusters_per_class=1)
    dist = pdist(X)

    plt.hist(dist, bins=30)
    plt.title(f"{d} Features")
    # plt.show()

"""Task 3 Numeric Preprocessing

Selected Features
"""

num_features = ['lead_time','adr','adults','children',
                'stays_in_week_nights','stays_in_weekend_nights']

"""Binning"""

df['lead_time_bin'] = pd.qcut(df['lead_time'], 4)
df['adr_bin'] = pd.cut(df['adr'], 5)

"""Binarization"""

df['high_value'] = (df['adr'] > 100).astype(int)

"""Scaling Comparision"""

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

scalers = [MinMaxScaler(), StandardScaler(), RobustScaler()]

for scaler in scalers:
    scaled = scaler.fit_transform(df[num_features])
    pd.DataFrame(scaled).hist(figsize=(8,5))
    plt.title(type(scaler).__name__)
    # plt.show()

"""Task 4: Distance/Proximity Metrics & Impact

Distance-Based Model (KNN - Classification)
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score

X_small = df[num_features]
y_small = df['is_canceled']

# Create a pipeline with an imputer and KNN classifier
knn_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('knn', KNeighborsClassifier(metric='euclidean'))
])

# Fit the pipeline on the training data
knn_pipeline.fit(X_train[num_features], y_train)

# Predict and evaluate
print("No scaling (with imputation):", f1_score(y_test, knn_pipeline.predict(X_test[num_features])))

"""WITH SCALING

"""

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score

# Create a pipeline with imputer, scaler, and KNN classifier
kkn_scaled_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier(metric='euclidean'))
])

# Fit the pipeline on the training data (original features)
kkn_scaled_pipeline.fit(X_train[num_features], y_train)

# Predict and evaluate on the test data (original features)
print("Standard (with imputation and scaling):", f1_score(y_test, kkn_scaled_pipeline.predict(X_test[num_features])))

"""TASK 5 -End-to-End Numeric Pipeline


"""

from sklearn.preprocessing import PowerTransformer

power_transform_cols = num_features
other_num_cols = [col for col in num_cols if col not in power_transform_cols]

pipeline = Pipeline([
    ("prep", ColumnTransformer([
        ("power_num", Pipeline([
            ("imp", SimpleImputer(strategy="median")),
            ("power", PowerTransformer(method='yeo-johnson')),
            ("scale", StandardScaler())
        ]), power_transform_cols),

        ("other_num", Pipeline([
            ("imp", SimpleImputer(strategy="median")),
            ("scale", StandardScaler())
        ]), other_num_cols),

        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
    ])),
    ("model", LogisticRegression(max_iter=1000))
])

pipeline.fit(X_train, y_train)

"""TASK 6: Feature Extraction

A) Date/Time features
"""

df['arrival_date'] = pd.to_datetime(
    df['arrival_date_year'].astype(str) + "-" +
    df['arrival_date_month'] + "-" +
    df['arrival_date_day_of_month'].astype(int).astype(str),
    format='%Y-%B-%d'
)

df['month'] = df['arrival_date'].dt.month
df['weekday'] = df['arrival_date'].dt.weekday
df['is_weekend'] = df['weekday'].isin([5,6]).astype(int)
df['quarter'] = df['arrival_date'].dt.quarter
df['lead_time_bucket'] = pd.qcut(df['lead_time'], 4)

print('DataFrame columns:')
print(df.columns.tolist())

print(f"'month' column exists: {'month' in df.columns}")
print(f"'weekday' column exists: {'weekday' in df.columns}")
print(f"'is_weekend' column exists: {'is_weekend' in df.columns}")
print(f"'quarter' column exists: {'quarter' in df.columns}")
print(f"'lead_time_bucket' column exists: {'lead_time_bucket' in df.columns}")

# For 'days between booking and arrival', this is implicitly handled by 'lead_time_bucket' and 'lead_time' itself.

"""TASK 7 FEAUTRE CONSTRUCTION

"""

df['total_nights'] = df['stays_in_week_nights'] + df['stays_in_weekend_nights']
df['total_people'] = df['adults'] + df['children'] + df['babies']

# ratios
df['price_per_person'] = df['adr'] / (df['total_people'] + 1)
df['requests_rate'] = df['total_of_special_requests'] / (df['total_nights'] + 1)

# interactions
df['adr_lead'] = df['adr'] * df['lead_time']
df['family_flag'] = (df['children'] + df['babies'] > 0).astype(int)

print('DataFrame columns after Task 7:')
print(df.columns.tolist())

new_features_task7 = [
    'total_nights', 'total_people', 'price_per_person',
    'requests_rate', 'adr_lead', 'family_flag', 'country_avg_price'
]

for feature in new_features_task7:
    print(f"'{feature}' column exists: {feature in df.columns}")

"""aggregation(train-only)

"""

country_avg = df.groupby('country')['adr'].mean()
df['country_avg_price'] = df['country'].map(country_avg)

"""TASK 8 FEATURE IMPORTANCE+SELECTION

FEATURE IMPORTANCE

PART A: Prepare Scaled Data First
"""

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# Create a preprocessing pipeline for the numerical features
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Apply the preprocessing to the selected numerical features in X_train and X_test
X_train_s = numeric_transformer.fit_transform(X_train[num_features])
X_test_s = numeric_transformer.transform(X_test[num_features])

print("X_train_s and X_test_s created successfully after imputation and scaling.")

"""RANDOM FOREST FEATURE IMPORTANCE"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train_s, y_train)

rf.feature_importances_

"""Mutual Info

"""

from sklearn.feature_selection import mutual_info_classif

mi = mutual_info_classif(X_train_s, y_train)
print("Mutual Information scores:", mi)

"""Permutation (bonus)

"""

# Define correlation matrix
corr = df[num_features].corr().abs()

"""Part B : Filter feature selection

Apply:
● Correlation filtering (remove redundant features above threshold e.g., 0.85)
● Chi-square (for non-negative encoded features)
● Mutual Information ranking

### Correlation Filtering
"""

# Select upper triangle of correlation matrix
uppertri = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

# Find features with correlation greater than 0.85
to_drop = [column for column in uppertri.columns if any(uppertri[column] > 0.85)]

print("Features to consider dropping due to high correlation (>0.85):")
if to_drop:
    print(to_drop)
else:
    print("No features with correlation greater than 0.85 found among selected numerical features.")

"""### Chi-square for non-negative encoded features"""

from sklearn.feature_selection import chi2
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

# Prepare categorical features for Chi-square
# We'll use X_train and y_train for this

# Create a pipeline for categorical features: impute and one-hot encode
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

X_train_cat_processed = cat_pipeline.fit_transform(X_train[cat_cols])

# Get feature names after one-hot encoding
ohe_feature_names = cat_pipeline.named_steps['onehot'].get_feature_names_out(cat_cols)

# Calculate Chi-square scores
chi2_scores, p_values = chi2(X_train_cat_processed, y_train)

# Create a DataFrame for better readability
chi2_df = pd.DataFrame({'Feature': ohe_feature_names, 'Chi2 Score': chi2_scores, 'P-value': p_values})
chi2_df = chi2_df.sort_values(by='Chi2 Score', ascending=False).reset_index(drop=True)

print("Top 10 Chi-square scores for categorical features:")
print(chi2_df.head(10))

"""### Mutual Information Ranking"""

mi_df = pd.DataFrame({'Feature': num_features, 'Mutual Information Score': mi})
mi_df = mi_df.sort_values(by='Mutual Information Score', ascending=False).reset_index(drop=True)

print("Mutual Information scores for numerical features:")
print(mi_df)

print("\nScript execution completed successfully!")